#!/bin/sh
#
# 首次启动后执行，进行一些默认设置。运行后会自动删除此脚本。
#

uci set luci.main.lang='zh_cn'
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci
# --- Dropbear ---
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear

# --- nginx 设置 ---
sed -i 's/deny all/allow all/g' /etc/nginx/restrict_locally
uci delete nginx._redirect2ssl.return
uci delete nginx._redirect2ssl.include
uci add_list nginx._redirect2ssl.include='restrict_locally'
uci add_list nginx._redirect2ssl.include='conf.d/*.locations'
uci commit nginx
/etc/init.d/nginx restart

# --- Cpufreq 设置 ---
uci batch << EOI
set cpufreq.cpufreq.governor0='schedutil'
set cpufreq.cpufreq.minfreq0='500000'
set cpufreq.cpufreq.maxfreq0='1512000'
EOI
uci commit cpufreq

# --- 启用 KMS 服务器 ---
uci batch << EOI
EOI


# --- 默认开启 Packet Steering ---
uci set network.globals.packet_steering='2'
uci set network.globals.steering_flows='256'
uci commit network

# --- 通用即插即用 ---

# --- bandix ---
uci set bandix.general.log_level='error'
uci commit bandix

# --- 计划任务 ---
uci set system.@system[0].cronloglevel="9"
uci commit system
/etc/init.d/cron restart

[ -d /usr/share/xray ] || mkdir -p /usr/share/xray
[ -f /usr/share/v2ray/geoip.dat ] && ln -sf /usr/share/v2ray/geoip.dat /usr/share/xray/geoip.dat
[ -f /usr/share/v2ray/geosite.dat ] && ln -sf /usr/share/v2ray/geosite.dat /usr/share/xray/geosite.dat


# --- Flag packages (禁止更新) ---
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full

# --- 禁用某些可能会自启动且用不上的依赖包服务 ---
/etc/init.d/haproxy disable 2>/dev/null
/etc/init.d/haproxy stop
/etc/init.d/kcptun disable 2>/dev/null
/etc/init.d/kcptun stop
/etc/init.d/sing-box disable 2>/dev/null
/etc/init.d/sing-box stop
/etc/init.d/ttyd disable 2>/dev/null
/etc/init.d/ttyd stop

# --- openwr_release 写入编译日期 ---
sed -i '/BUILD_DATE/d' /etc/openwrt_release
echo "BUILD_DATE='build_date'" >> /etc/openwrt_release

# --- 清除 LuCI 残留缓存 ---
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0
